port: "8080"

db:
  driver: "mysql"
  host: "localhost"
  port: "3306"
  user: "user"
  password: "password"
  name: "assignment"

cors:
  allow_origins: "*"
  allow_methods: "GET, POST, PUT, DELETE"
  allow_headers: "Origin, Content-Type, Accept, Authorization"
