port: "8080"

db:
  driver: "mysql"
  host: "localhost"
  # host: "kasikorn-line-api-mysql-container"
  port: "3306"
  user: "user"
  password: "password"
  name: "kasikorn_line"

cors:
  allow_origins: "*"
  allow_methods: "GET, POST, PUT, DELETE"
  allow_headers: "Origin, Content-Type, Accept, Authorization"

rate_limiter:
  max_requests: 20        
  expiration: 30