// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/repositories/user_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "kasikorn-line-api/internal/user/repositories/models"
	error "kasikorn-line-api/pkg/error"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(userID string) (*models.User, *error.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*error.ErrorResponse)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), userID)
}

// GetUserGreetingByUserID mocks base method.
func (m *MockUserRepository) GetUserGreetingByUserID(userID string) (*models.UserGreeting, *error.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGreetingByUserID", userID)
	ret0, _ := ret[0].(*models.UserGreeting)
	ret1, _ := ret[1].(*error.ErrorResponse)
	return ret0, ret1
}

// GetUserGreetingByUserID indicates an expected call of GetUserGreetingByUserID.
func (mr *MockUserRepositoryMockRecorder) GetUserGreetingByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGreetingByUserID", reflect.TypeOf((*MockUserRepository)(nil).GetUserGreetingByUserID), userID)
}
